CREATE TABLE matcha.USER(ID MEDIUMINT AUTO_INCREMENT, CONFIRM VARCHAR(55), NAME VARCHAR(30), LASTNAME VARCHAR(30),
            MIDDLENAME VARCHAR(30), BIRTHDAY DATE, YEARS_OLD MEDIUMINT,
            EMAIL VARCHAR(30), PASSWORD VARCHAR(255), LOCATION VARCHAR(180), USER_CARD MEDIUMINT, FILTER_PARAMS MEDIUMINT, PRIMARY KEY (ID));

CREATE TABLE matcha.USER_CARD(ID MEDIUMINT AUTO_INCREMENT, BIOGRAPHY varchar(300), WORKPLACE varchar(70),
            POSITION varchar(70), EDUCATION VARCHAR(120), GENDER VARCHAR(40), SEXUAL_PREFERENCE VARCHAR(40), TAGS VARCHAR(150), RATING DOUBLE, PHOTOS_PARAMS VARCHAR(32),
            MAIN_PHOTO MEDIUMINT, USER_ID MEDIUMINT, PRIMARY KEY (ID));

CREATE TABLE matcha.LINK(ID MEDIUMINT AUTO_INCREMENT, URL VARCHAR(200), OPEN MEDIUMINT, PRIMARY KEY (ID));

CREATE TABLE matcha.JWT(ID MEDIUMINT AUTO_INCREMENT, USER_ID MEDIUMINT, TOKEN VARCHAR(400), TYPE VARCHAR(30) PRIMARY KEY (ID));

CREATE TABLE matcha.LIKES_ACTION(ID MEDIUMINT AUTO_INCREMENT, CREATION_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP, FROM_USR MEDIUMINT, TO_USR MEDIUMINT, ACTION VARCHAR(30), PRIMARY KEY (ID));

CREATE TABLE matcha.FILTER_PARAMS(ID INTEGER AUTO_INCREMENT, AGE_BY MEDIUMINT, AGE_TO MEDIUMINT, RATING DOUBLE,
            COMMON_TAGS_COUNT MEDIUMINT, PRIMARY KEY(ID));

CREATE TABLE matcha.WEB_SOCKET_MESSAGE(ID MEDIUMINT, CREATION_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP(6), CHAT_ID MEDIUMINT, FROM_ID MEDIUMINT, TO_ID MEDIUMINT, TYPE VARCHAR(30), STATUS VARCHAR(30), CONTENT BLOB, PRIMARY KEY (ID));

CREATE TABLE matcha.CHAT_AFFILIATION(ID MEDIUMINT AUTO_INCREMENT, CREATION_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP(6), FROM_USR MEDIUMINT, FROM_TO MEDIUMINT, CHAT_ID MEDIUMINT, PRIMARY KEY (ID));